### ISSUE TITLE
1.9-0.2.1 crashes client on startup using forge 1.9 build 1811

### ISSUE THREAD

**Issue by kreezxil** [maruohon/itemscroller#1]
fml latest: http://paste.ee/p/Xitf3

crash report: http://paste.ee/p/jqIaO

**Comment by maruohon** [comment]
Yeah apparently they did several changes in Forge 1805 that broke many mods... I guess I'll have to go through all of my 1.9 ports as well... Thanks for the report, didn't even realize it broke my small mods as well.

**Comment by maruohon** [comment]
This has now been fixed in version 0.2.2 for MC 1.9.
