### ISSUE TITLE
Scrolling not working properly

### ISSUE THREAD

**Issue by PapiDimmi** [maruohon/itemscroller#15]
I can only scroll one item at a time unless I scroll really fast.

**Modpack**: [The Simple Life 2](https://minecraft.curseforge.com/projects/the-simple-life-2-hqm), version 1.4
**Minecraft version**: 1.10.2
**Forge version**: 12.18.3.2511
**Item Scroller version**: 0.11.0

**Comment by maruohon** [comment]
That pack doesn't seem to have Item Scroller, but instead Mouse Tweaks. Did you remove Mouse Tweaks or at least disable the scrolling feature from it? Otherwise they would likely interfere with each other.

**Comment by PapiDimmi** [comment]
I totally forgot that I manually added Item Scroller to the modpack, and I had no idea that Mouse Tweaks had a scrolling feature. I guess I’ll just remove Item Scroller or disable the scrolling feature in Mouse Tweaks.

Thanks.
