### ISSUE TITLE
Crash when using  Computacube/Computer Craft

### ISSUE THREAD

**Issue by MinoCraft** [maruohon/itemscroller#16]
Hello o/

I play with Minecraft 1.12.2 and a personnal modpack.

In my instance, I have, Forge 14.23.2.2627, Computacube 1.80pr1 v1.2 and Item Scroller 0.11.0
When I'm using a computer, some times have a crash. You can see more détail in the crash report
[crash-2018-03-22_22.15.21-client.txt](https://github.com/maruohon/itemscroller/files/1839318/crash-2018-03-22_22.15.21-client.txt)

Thanks in advance for the fix !

**Comment by maruohon** [comment]
I have seen this crash a few times before, but I have no idea what causes it...

* What do you have the Item Scroller keybind set to?
* When *exactly* does this crash occur, and in what GUI?
* Where you scrolling the mouse, holding down any keys, or had you just pressed down any key when the crash happens?

**Comment by maruohon** [comment]
This should be fixed in 0.12.0.
