### ISSUE TITLE
Crash while trying to craft anything

### ISSUE THREAD

**Issue by MCEventHorizon** [maruohon/itemscroller#22]
Right after the crafting output is supposed to be shown, the game crashes.

[crash-2019-07-05_18.49.31-client.txt](https://github.com/maruohon/itemscroller/files/3363527/crash-2019-07-05_18.49.31-client.txt)

**Comment by maruohon** [comment]
The 1.14.2 version of Item Scroller won't work on 1.14.3, due to one single change in vanilla that affected the mod... which is exactly that line that crashes for you. I guess I should upload the 1.14.3 versions to CurseForge as well, thus far they have just been on my server.
