### ISSUE TITLE
Method overwrite conflict for getSlotIndex

### ISSUE THREAD

**Issue by calloatti** [maruohon/itemscroller#25]
itemscroller-fabric-1.14.4-0.15.0-dev.20190720.190250.jar
tweakeroo-fabric-1.14.4-0.9.10.jar

[main/WARN]: Method overwrite conflict for getSlotIndex in mixins.tweakeroo.json:IMixinSlot, previously written by fi.dy.masa.itemscroller.mixin.IMixinSlot. Skipping method.

https://github.com/maruohon/tweakeroo/issues/11

**Comment by maruohon** [comment]
See https://github.com/maruohon/tweakeroo/issues/11
