### ISSUE TITLE
Crash on launch with Forge version 28.1.61

### ISSUE THREAD

**Issue by yungwilder** [maruohon/itemscroller#26]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

---
this is with no other mods in the mods folder using file version: 
itemscroller-forge-1.14.4-0.15.0-dev.20191023.012451

**Comment by yungwilder** [comment]
https://pastebin.com/u3VTivnK

@maruohon let me know if you need a renewed paste bin link.

**Comment by maruohon** [comment]
This version also needs the malilib library mod, like all the other recent versions do.

**Comment by yungwilder** [comment]
Am I missing the Forge version of that library?

**Comment by maruohon** [comment]
Yes: https://www.curseforge.com/minecraft/mc-mods/malilib/files/2814629

**Comment by yungwilder** [comment]
This snippet from the Twitch mod page may need to be adjusted as well:
"The LiteLoader, Rift and Fabric versions require the MaliLib library mod: "

**Comment by yungwilder** [comment]
Ah, I see now, It was not showing unless I selected View All. Ty

**Comment by yungwilder** [comment]
Launch success, closing issue.
