### ISSUE TITLE
Causes a crash when starting MC 1.14.4 (Forge)

### ISSUE THREAD

**Issue by SepSol** [maruohon/itemscroller#27]
When I start the game after the Forge loading screen the game crashes. Here's the [debug.log](https://gist.github.com/SepSol/afdb6f48f2b93451bf5ef3983e6dea38).

======================
Minecraft 1.14.4
Forge 28.1.61
Item Scroller 15.0-dev.20191023.012451

**Comment by vacla** [comment]
do you have malilib installed?

**Comment by SepSol** [comment]
You stated that only the Fabric, Rift and LiteLoader versions require MaLib 🤔 

![image](https://user-images.githubusercontent.com/47871887/67365137-e6003080-f57d-11e9-82e9-7d2bba864fbf.png)

**Comment by vacla** [comment]
you need it for all his mods

**Comment by SepSol** [comment]
Ok, I'll give it a try then

**Comment by SepSol** [comment]
Yeah it worked, it needed MaliLib. So please correct the wording in your curseforge page. :)

**Comment by maruohon** [comment]
I edited the description now... forgot to check that yesterday when uploading the Forge version. Also forgot to add the dependency to the mod itself so that Forge would tell you, so I'll do that later today.

**Comment by SepSol** [comment]
Perfect!
