### ISSUE TITLE
Disables JEI hide item functionality

### ISSUE THREAD

**Issue by MysticAura** [maruohon/itemscroller#3]
MC Version: 1.10.2
Forge Version: 2007 & 2008
Mod Version: 1.10.2-0.5.1

Adding this mod to my pack makes JEI's hide item functionality, unusable.

Steps to Reproduce: Install this mod, attempt to hide item in JEI in proper mode, nothing happens.
Uninstalling returns functionality.

**Comment by maruohon** [comment]
This has now been fixed in 0.5.2. Thanks for reporting it!
