### ISSUE TITLE
Causes a crash when using with Quark mod (1.14.4)

### ISSUE THREAD

**Issue by SepSol** [maruohon/itemscroller#30]
Whenever I launch the game with this mod beside the new [Quark ](https://www.curseforge.com/minecraft/mc-mods/quark)mod for 1.14.4, the game crashes and exits before even showing the FML splash screen. Here's the [Crash Report](https://gist.github.com/SepSol/90b5a52e8984d382d1f19549c457d44a).

**SPECS**
Minecraft 1.14.4
Forge 28.1.85
itemscroller-forge-1.14.4-0.15.0-dev.20191023.012451
Quark-r2.0-198

**Comment by vacla** [comment]
do you have malilib?

**Comment by SepSol** [comment]
No, I forgot it. That was my bad. It is fixed now, thx.
