### ISSUE TITLE
no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no

### ISSUE THREAD

**Issue by TheoBuzz** [maruohon/itemscroller#38]
this is stupid forge is already good this is bad fuck you delete this shit ur fabruc sucks use forge mother fuckers fabric sucks forge is perfect awesome good for mod needs no fabric is hacks hacks HACKS mixins stupid kill your self im gay btw

**Comment by maruohon** [comment]
Thank you for your invaluable feedback. Unfortunately I have to disagree, Fabric is actually a LOT nicer and easier to work with and also allows me to do things that are not possible/as easy to do with Forge before it gets Mixin support.

Also Item Scroller was originally a Forge mod, and there still is a Forge version as well, as well as LiteLoader and Rift versions. Do you still want me to delete this shit just to be sure there is nothing except your precious Forge around?
