### ISSUE TITLE
Item Scroller doesn't load

### ISSUE THREAD

**Issue by zLauch** [maruohon/itemscroller#39]
Sometimes Item Scroller doesn't load at all.
I have to restart Minecraft and even then it doesn't load (sometimes).

version: v0.15.0-dev.20200624214738

**Comment by vacla** [comment]
Malilib?

**Comment by maruohon** [comment]
How did you determine it doesn't load? If you mean that it doesn't work, then you might have accidentally used the main toggle hotkey that disables all the functionality, which is by default `Ctrl + S` while inside an inventory GUI. I really need to remove that hotkey by default...

**Comment by zLauch** [comment]
first of all i updated to the newst version an i'll see how it's doing.
but i this have some questions.

can i ask 'em on discord if you have?

**Comment by maruohon** [comment]
Yes, there is a `#masas-mods` channel on the SciCraft discord: https://discord.gg/scicraft
