### ISSUE TITLE
Copy-paste doesn't work in the anvil GUI

### ISSUE THREAD

**Issue by Heitzenberg** [maruohon/itemscroller#51]
I recently noticed that I can't copy-paste text into an anvil anymore. Without itemscroller, it's working fine. Is this a config issue or something else?

(itemscroller-fabric-1.16.4-0.15.0-dev.20210111.205029)

**Comment by maruohon** [comment]
I can't reproduce that, I can still paste normally in the Anvil GUI.
What other mods do you have?

https://user-images.githubusercontent.com/2331050/107980704-65aedb80-6fc9-11eb-8e60-1e2e919cc976.mp4

**Comment by Heitzenberg** [comment]
Strange.. This is my mod list: 
![image](https://user-images.githubusercontent.com/44086264/107980800-28dee680-6fc1-11eb-99ae-89268d41f96a.png)

When I remove itemscroller, it's working fine. Must be an incompatibility with another mod then.

**Comment by maruohon** [comment]
I guess first try if it still is an issue if you remove Appleskin, Fast Chest, g4mespeed, Shulker Box Tooltip.
Also I guess before that, have you changed any of the hotkeys, maybe something bound to V in Item Scroller, with the Cancel Further Processing enabled?

**Comment by Heitzenberg** [comment]
"Also I guess before that, have you changed any of the hotkeys, maybe something bound to V in Item Scroller, with the Cancel Further Processing enabled?"

That was it! Thanks for the help, and sorry for the hassle.
