### ISSUE TITLE
Does Item Scroller work in 1.16.5?

### ISSUE THREAD

**Issue by James103** [maruohon/itemscroller#54]
The latest file `itemscroller-fabric-1.16.4-0.15.0-dev.20210111.205029.jar` only says that it works in Minecraft 1.16.4 according to the file name. Does this work in 1.16.5, or will that support be in the next version?

**Comment by greetingsuniverse** [comment]
It works in 1.16.5 yes any mod for 1.16.4 should work in 1.16.5

**Comment by maruohon** [comment]
I'm still building the mods against 1.16.4, that's why it says 1.16.4 in the file name. But the 1.16.4 versions of all my client mods should work in all MC versions between 1.16.2 - 1.16.5, that's also why I haven't bothered updating my dev environment to 1.16.5 yet.
