### ISSUE TITLE
I cant save any recipe's 

### ISSUE THREAD

**Issue by Dclones** [maruohon/itemscroller#66]
When I first tried to save a recipe which was a gold ingot it worked perfectly but after that, it stopped saving recipes and now I can't save recipes or use any of the crafting features like mass craft etc... but the rest of the mod works I thought maybe it was my scroll wheels fault so I changed the bind to R but that doesn't do anything and whenever I do try to save anything it will just give my player the items from the crafting grid back.

**Comment by maruohon** [comment]
So I take it you didn't accidentally disable the mod features with `Ctrl + S` while inside an inventory GUI, if the other things still work?
Do you get the recipe storage view when you hold `A`? You need to have that view open while saving a recipe.

**Comment by Dclones** [comment]
> So I take it you didn't accidentally disable the mod features with `Ctrl + S` while inside an inventory GUI, if the other things still work?
> Do you get the recipe storage view when you hold `A`? You need to have that view open while saving a recipe.

**Comment by Dclones** [comment]
> So I take it you didn't accidentally disable the mod features with `Ctrl + S` while inside an inventory GUI, if the other things still work?
> Do you get the recipe storage view when you hold `A`? You need to have that view open while saving a recipe.

yes I didn't disable it and yes I do get the storage view when I hold A

**Comment by maruohon** [comment]
And you are using the pick block key (usually middle click) while hovering over the crafting grid output item, while also holding the recipe view open, and nothing happens?

**Comment by Dclones** [comment]
> And you are using the pick block key (usually middle click) while hovering over the crafting grid output item, while also holding the recipe view open, and nothing happens?

Omg, thank you I didn't know you had to use pick block on the item being crafted I thought I had to press it on the recipe storage slot you wanted. Sorry for wasting your time

**Comment by maruohon** [comment]
It works this way in case there are multiple crafting grids within the same inventory, so that the mod knows which grid you want to use for the recipe (although this is only the case in some modded inventories).
