### ISSUE TITLE
Is itemscroller not in your maven?

### ISSUE THREAD

**Issue by fooeyround** [maruohon/itemscroller#67]
I am Making a Mod to Help with afk Void Trading For A Server I am on, But it seems I cant link it thru too your maven, am I wrong? Should I just download it myself Instead of generating it from the auto download?

**Comment by maruohon** [comment]
There haven't really been any extension mods for Item Scroller thus far, so I don't usually push it (or any other mods for that matter, except for malilib) to my maven.

You can add it as a local library dependency via your mod's `build.gradle`, or you could use the Curse maven to pull it from CurseForge. Example: https://github.com/plusls/MasaGadget/blob/b1a07ae16c2a895e3afa5763545480eb95819fd3/build.gradle

**Comment by fooeyround** [comment]
Ok thx
