### ISSUE TITLE
[Mod compat] [Bug] clientCraftingFixOn1.12 prevents crafting inventory from being altered during crafting

### ISSUE THREAD

**Issue by vlad2305m** [maruohon/itemscroller#69]
`itemscroller-fabric-1.17.1-0.15.0-dev.20210707.005506`
So I made a recipe that consumes the stack as soon as you check for it (or `craft()` it), always outputting `ItemStack.EMPTY`.
I have no idea why, but your fix completely reverts the changes made by the recipe, which you can see from the flicker of the item while updating the recipe. (Ideally, the second check retuns no recipe found, and result stack is empty anyway, so there is no need to set it to air again as you do in `onSlotChangedCraftingGrid()`, but the issue can lie somewhere else)
https://youtu.be/36_J0hjAOn0

**Comment by maruohon** [comment]
Can you check if this version fixes it or changes anything? https://www.curseforge.com/minecraft/mc-mods/item-scroller/files/3542814

It should now not set an empty stack to the slot in that code.

**Comment by vlad2305m** [comment]
Works flawlessly. Thank you!
