### ISSUE TITLE
Conflict with Applied Energistics

### ISSUE THREAD

**Issue by Xiaminou** [maruohon/itemscroller#7]
When browsing an Applied Energistics Terminal this mods prevents you from scrolling through the list while pointing at an item, and prevents you from shift+right-clicking an item to pick up only one item.

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2627

#### Environment
- Minecraft Version: 1.10.2
- Forge Version: 2135

**Comment by maruohon** [comment]
In my testing the scrolling works just fine with AE2 and Item Scroller. I now fixed my drag handler to use stricter checking for when to cancel the mouse input event, which fixes the shift + right click issue in a AE2 Terminal.

**Comment by Xiaminou** [comment]
Really? That's strange, I used the latest version available with only AE2 and JEI and I could not scroll while pointing at items.

**Comment by maruohon** [comment]
Really? Huh. Why would that be... I was testing with the ME Terminal and the list scrolled just fine while hovering over the items, or the scroll bar.

**Comment by Xiaminou** [comment]
I will have to try again then.

**Comment by Xiaminou** [comment]
So, today my scrolling reflex kicked in and I realized I had forgotten to re-add this mod to my pack and in the process forgot to check if there was still an issue with it. I can confirmed that it's working properly now, thank you.

**Comment by Xiaminou** [comment]
Can't shift+right-click to pick up 1 item in Applied Energistics Terminals with versions 0.9.0 and 0.9.1.

**Comment by maruohon** [comment]
I added Slot and GUI blacklists in 0.10.0 and the ME Terminal slots are now blacklisted by default, along with TiCo Crafting Station side inventory slots. Beyond those I have no idea which mods/inventories/slots may be problematic so I'll leave adding any others to the blacklist to users and mod pack makers...

Adding stuff to the blacklist can be done via the in-game config menu, and the slot class or the GUI class name can be seen from the also-newly-added debug key combination Ctrl+Alt+Shift + I while hovering over a slot (or while NOT hovering over a slot to get the GUI class name).

**Comment by Xiaminou** [comment]
Good to know, thanks.
