### ISSUE TITLE
1.18.2 hotkeys not working

### ISSUE THREAD

**Issue by masterofjavascript** [maruohon/itemscroller#77]
The hotkeys do not work, the scrolling does yet when I hold shift it doesn't do whole stacks

If you need more info pls tell me as i am new to this

**Comment by maruohon** [comment]
Do you have Optifine? It apparently breaks all malilib hotkeys now...

**Comment by masterofjavascript** [comment]
ah thanks, i just removed optifine and it worked, thanks a lot
