### ISSUE TITLE
Does your mod supports item re-filling?

### ISSUE THREAD

**Issue by aleck099** [maruohon/itemscroller#88]
Pick the same tool from the inventory to main hand when current tool breaks up
Pick the same item from the inventory to main hand when current item is used up
Pick the same block from the inventory to main hand when current block is used up

**Comment by maruohon** [comment]
These are not part of Item Scroller. The Tweakeroo mod has a "Hand Restock" feature, which re-fills the hand slot when items (blocks) are used up (and by default it fills the slot a bit before it runs out, which helps in avoiding some inventory de-syncs, although they can still happen especially if you have a high ping to the server).

That feature doesn't work for tools though, but there is a separate "Swap Almost Broken Tools" feature which would prevent them from being completely used up and fetch a new replacement before it breaks.

**Comment by aleck099** [comment]
> These are not part of Item Scroller. The Tweakeroo mod has a "Hand Restock" feature, which re-fills the hand slot when items (blocks) are used up (and by default it fills the slot a bit before it runs out, which helps in avoiding some inventory de-syncs, although they can still happen especially if you have a high ping to the server).
> 
> That feature doesn't work for tools though, but there is a separate "Swap Almost Broken Tools" feature which would prevent them from being completely used up and fetch a new replacement before it breaks.

Thank you
