### ISSUE TITLE
Mod stops working after a while

### ISSUE THREAD

**Issue by tomosmc** [maruohon/itemscroller#90]
As the title suggests, when being in my server, the itemscroller sometimes suddenly stops working. The hotkeys to scroll over items all don't work anymore and the mass crafting gui also doesn't show up when pressing it's hotkey in a crafting table. I've found the only solution to be, to restart the game, which is quite annoying. I understand that this is difficult to replicate, but I'd like to know if there are any fixes for this. All my mods are in the image. [https://imgur.com/QOQio5r](url)

>

**Comment by maruohon** [comment]
You are probably accidentally using the hotkey to toggle off the mod functionality, which I think is still `Ctrl + S` while inside an inventory GUI. You probably want to unbind that hotkey, and I'll also remove that default key when I remember to do it.

**Comment by tomosmc** [comment]
Yoo tysm for the quick response, unbinding the keybind solved the issue! Love your mods!
