### ISSUE TITLE
Mass crafting recipe view doesn't save over sessions

### ISSUE THREAD

**Issue by MqcCheeze** [maruohon/itemscroller#98]
![image](https://user-images.githubusercontent.com/87596784/221655680-dd9b4efa-6b42-41d1-a106-6fffdf724c8b.png)

When I close Minecraft for the day and come back the next day, or a crash occurs, the recipe view doesn't save the crafting recipes I've created. Is this an issue or a feature, and is there anyway to disable it clearing itself upon exit

**Comment by maruohon** [comment]
The recipes are supposed to get saved.

First check that you don't have the `I + C` -> Generic -> `craftingRecipesSaveToFile` option disabled.
![image](https://user-images.githubusercontent.com/2331050/221657978-c0742894-239c-4fbb-ab16-2c7cb81719f7.png)

Next check if you have a file in `.minecraft/itemscroller/` corresponding to your world or server name. I think one case that might be problematic is if you play on a Realm server ,as they don't have static IPs. If it's an issue with some special characters in the world name or you are on a Realm, then you can try enabling the other shown option, `craftingRecipesSaveFileIsGlobal`. That would not use a per-world or per-server file name but just a common file name, which would also mean the recipes are shared between any worlds you play in.

**Comment by MqcCheeze** [comment]
Nice, it works now, I must have disabled it by accident randomly. Thanks
